<?php
/**
 * BatchApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BatchApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for postCrmV3ObjectsContactsBatchArchiveArchive
     *
     * Archive a batch of contacts by ID.
     *
     */
    public function testPostCrmV3ObjectsContactsBatchArchiveArchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCrmV3ObjectsContactsBatchCreateCreate
     *
     * Create a batch of contacts.
     *
     */
    public function testPostCrmV3ObjectsContactsBatchCreateCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCrmV3ObjectsContactsBatchReadRead
     *
     * Read a batch of contacts by internal ID, or unique property values.
     *
     */
    public function testPostCrmV3ObjectsContactsBatchReadRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCrmV3ObjectsContactsBatchUpdateUpdate
     *
     * Update a batch of contacts.
     *
     */
    public function testPostCrmV3ObjectsContactsBatchUpdateUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
